# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update package lists
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Print Hello, World! when the container runs
CMD ["echo", "Hello, World!"]
